MACOSX_DEPLOYMENT_TARGET:  # [osx]
  - "10.11"                # [osx and not arm64]
  - "11.3"                 # [arm64]
MACOSX_SDK_VERSION:        # [osx]
  - "10.11"                # [osx and not arm64]
  - "11.3"                 # [arm64]
