{% set version = "7.3" %}
{% set name = "pyobjc-framework-Metal" %}

package:
  name: pyobjc-framework-metal
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 249d996476cee9e8762839b16d6fcfedd4acd3195fe1ef436aa6e3806177db37

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [(not osx) or py2k or python_impl == 'pypy' or (arm64 and py < 39)]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - pyobjc-core ={{ version }}
    - pyobjc-framework-cocoa ={{ version }}
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.11") }}  # [osx]

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - Metal

about:
  home: https://bitbucket.org/ronaldoussoren/pyobjc
  license: MIT
  license_file: LICENSE.txt
  summary: Wrappers for the Metal framework on macOS

extra:
  recipe-maintainers:
    - leofang
