{% set version = "12.1" %}
{% set name = "pyobjc-framework-Metal" %}

package:
  name: pyobjc-framework-metal
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name.replace('-', '_').lower() }}/{{ name.replace('-', '_').lower() }}-{{ version }}.tar.gz
  sha256: bb554877d5ee2bf3f340ad88e8fe1b85baab7b5ec4bd6ae0f4f7604147e3eae7

build:
  number: 0
  script:
    # force pyobjc to use conda-forge's chosen SDK
    - export CFLAGS="${CFLAGS} -isysroot ${SDKROOT:-$CONDA_BUILD_SYSROOT}"
    - {{ PYTHON }} -m pip install . -vv
  skip: true  # [not osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - libffi
  run:
    - python
    - pyobjc-core ={{ version }}
    - pyobjc-framework-cocoa ={{ version }}
    - libffi

test:
  requires:
    - pip
  commands:
    - python -c "import Metal; print(Metal.MTLCreateSystemDefaultDevice())"
  imports:
    - Metal

about:
  home: https://github.com/ronaldoussoren/pyobjc
  license: MIT
  license_file: LICENSE.txt
  summary: Wrappers for the Metal framework on macOS
  doc_url: https://pyobjc.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - xhochy
