{% set version = "10.0" %}
{% set name = "pyobjc-framework-Metal" %}

package:
  name: pyobjc-framework-metal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2e50b1fc34b11654a0ecb0d6ea98f691dc5794c53e18cb70f71d6460f68dbbf3

build:
  number: 0
  script:
    # force pyobjc to use conda-forge's chosen SDK
    - export CFLAGS="${CFLAGS} -isysroot ${SDKROOT:-$CONDA_BUILD_SYSROOT}"
    # force ignoring invalid compiler flag (-Wl,-export-dynamic)
    - export CFLAGS="${CFLAGS} -Wno-unused-command-line-argument"  # [py == 37 or py == 38]
    - {{ PYTHON }} -m pip install . -vv
  skip: true  # [(not osx) or py2k or python_impl == 'pypy' or (arm64 and py < 39)]

requirements:
  build:
    - {{ compiler('c') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - libffi
  run:
    - python
    - pyobjc-core ={{ version }}
    - pyobjc-framework-cocoa ={{ version }}
    - libffi
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.11") }}  # [osx]

test:
  requires:
    - pip
  commands:
    - python -c "import Metal; print(Metal.MTLCreateSystemDefaultDevice())"
  imports:
    - Metal

about:
  home: https://github.com/ronaldoussoren/pyobjc
  license: MIT
  license_file: LICENSE.txt
  summary: Wrappers for the Metal framework on macOS
  doc_url: https://pyobjc.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - xhochy
